### PR TITLE
Remesh speed improvements

### PR DESCRIPTION
**Pull request by zacsimile**
Some minor improvements to remesh.

Current stats on `test_er_data.hdf`

```
        1620971 function calls (1606453 primitive calls) in 5.470 seconds

   Ordered by: internal time
   List reduced from 1311 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    20053    0.847    0.000    0.890    0.000 _triangle_mesh.pyx:910(edge_collapse)
    17561    0.559    0.000    0.952    0.000 _triangle_mesh.pyx:1364(edge_split)
3381/2432    0.477    0.000    0.661    0.000 dual_marching_cubes.py:673(vert_proc)
        5    0.446    0.089    0.499    0.100 _triangle_mesh.pyx:1851(relax)
    15623    0.403    0.000    0.419    0.000 {method 'fix_empty_nodes' of 'PYME.experimental._octree.Octree' objects}
    53447    0.276    0.000    0.276    0.000 {method 'reduce' of 'numpy.ufunc' objects}
       41    0.262    0.006    0.319    0.008 _triangle_mesh.pyx:1793(regularize)
    32208    0.145    0.000    0.422    0.000 dual_marching_cubes.py:140(subdivided)
      976    0.134    0.000    0.134    0.000 weakiddict.py:26(_remover)
    17561    0.126    0.000    0.136    0.000 _triangle_mesh.pyx:1328(_new_vertex)
    40820    0.114    0.000    0.114    0.000 {built-in method numpy.array}
     4986    0.111    0.000    0.527    0.000 dual_marching_cubes.py:175(<listcomp>)
        1    0.100    0.100    0.103    0.103 _triangle_mesh.pyx:524(_initialize_halfedges)
   105366    0.065    0.000    0.098    0.000 _triangle_mesh.pyx:1252(_insert_new_edge)
68879/68252    0.053    0.000    0.517    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
    32481    0.052    0.000    0.207    0.000 fromnumeric.py:70(_wrapreduction)
       10    0.051    0.005    0.155    0.016 {built-in method Update}
    19060    0.042    0.000    0.042    0.000 _triangle_mesh.pyx:1517(edge_flip)
       21    0.041    0.002    0.041    0.002 {method 'sort' of 'numpy.ndarray' objects}
   158049    0.037    0.000    0.043    0.000 _triangle_mesh.pyx:1167(_get_insertion_slot)
```

and new stats, with this PR...

```

         1628103 function calls (1613595 primitive calls) in 3.755 seconds

   Ordered by: internal time
   List reduced from 1312 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
3381/2432    0.466    0.000    0.644    0.000 dual_marching_cubes.py:673(vert_proc)
    15623    0.360    0.000    0.375    0.000 {method 'fix_empty_nodes' of 'PYME.experimental._octree.Octree' objects}
       40    0.228    0.006    0.271    0.007 _triangle_mesh.pyx:1904(regularize)
       51    0.203    0.004    0.206    0.004 _triangle_mesh.pyx:445(__get__)
       51    0.202    0.004    0.205    0.004 _triangle_mesh.pyx:426(__get__)
    36021    0.165    0.000    0.165    0.000 {method 'reduce' of 'numpy.ufunc' objects}
    32208    0.142    0.000    0.414    0.000 dual_marching_cubes.py:140(subdivided)
    40810    0.110    0.000    0.110    0.000 {built-in method numpy.array}
    18109    0.109    0.000    0.339    0.000 _triangle_mesh.pyx:1442(edge_split)
      976    0.107    0.000    0.107    0.000 weakiddict.py:26(_remover)
     4986    0.105    0.000    0.479    0.000 dual_marching_cubes.py:175(<listcomp>)
        1    0.101    0.101    0.105    0.105 _triangle_mesh.pyx:524(_initialize_halfedges)
    20670    0.101    0.000    0.140    0.000 _triangle_mesh.pyx:910(edge_collapse)
    18109    0.096    0.000    0.104    0.000 _triangle_mesh.pyx:1406(_new_vertex)
   108654    0.059    0.000    0.088    0.000 _triangle_mesh.pyx:1330(_insert_new_edge)
        5    0.055    0.011    0.487    0.097 _triangle_mesh.pyx:1962(relax)
    32616    0.052    0.000    0.206    0.000 fromnumeric.py:70(_wrapreduction)
68974/68357    0.048    0.000    0.490    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
       10    0.038    0.004    0.118    0.012 {built-in method Update}
   162981    0.031    0.000    0.038    0.000 _triangle_mesh.pyx:1245(_get_insertion_slot)
```

### CODE REVIEW

**Comment by zacsimile** [comment]
Actually I just made things a lot faster by switching 

```
score_pre = abs(v1) + abs(v2) + abs(v3) + abs(v4)
score_post = abs(v1-1) + abs(v2-1) + abs(v3+1) + abs(v4+1)
```

to 

```
score_pre = v1*v1 + v2*v2 + v3*v3 + v4*v4
score_post = (v1-1)*(v1-1) + (v2-1)*(v2-1) + (v3+1)*(v3+1) + (v4+1)*(v4+1)
```

Since we only check `score_post < score_pre`, I think this should be OK.

**Comment by zacsimile** [comment]
New benchmark with the regularization fix on `test_er_data_uncropped.hdf`.

Master branch:

```
         19697520 function calls (19651348 primitive calls) in 80.709 seconds

   Ordered by: internal time
   List reduced from 1311 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   397262   17.228    0.000   18.104    0.000 _triangle_mesh.pyx:910(edge_collapse)
        5   12.130    2.426   13.300    2.660 _triangle_mesh.pyx:1851(relax)
   350017   10.430    0.000   18.167    0.000 _triangle_mesh.pyx:1364(edge_split)
       47   10.397    0.221   11.791    0.251 _triangle_mesh.pyx:1793(regularize)
   529547    2.971    0.000    2.971    0.000 {method 'reduce' of 'numpy.ufunc' objects}
17956/12627    2.822    0.000    3.932    0.000 dual_marching_cubes.py:673(vert_proc)
   350017    2.461    0.000    2.775    0.000 _triangle_mesh.pyx:1328(_new_vertex)
        1    2.088    2.088    2.142    2.142 _triangle_mesh.pyx:524(_initialize_halfedges)
    84961    2.037    0.000    2.128    0.000 {method 'fix_empty_nodes' of 'PYME.experimental._octree.Octree' objects}
   377478    1.370    0.000    1.370    0.000 _triangle_mesh.pyx:1517(edge_flip)
  2100102    1.286    0.000    1.955    0.000 _triangle_mesh.pyx:1252(_insert_new_edge)
    26860    0.912    0.000    2.992    0.000 dual_marching_cubes.py:175(<listcomp>)
   219196    0.869    0.000    0.869    0.000 {built-in method numpy.array}
  3150153    0.851    0.000    0.959    0.000 _triangle_mesh.pyx:1167(_get_insertion_slot)
      237    0.795    0.003    0.795    0.003 {method 'sort' of 'numpy.ndarray' objects}
   161160    0.759    0.000    2.185    0.000 dual_marching_cubes.py:140(subdivided)
       12    0.682    0.057    0.682    0.057 {method 'argsort' of 'numpy.ndarray' objects}
        6    0.660    0.110    0.664    0.111 _triangle_mesh.pyx:445(__get__)
        5    0.659    0.132   18.764    3.753 _triangle_mesh.pyx:2012(collapse_edges)
        6    0.518    0.086    0.519    0.087 _triangle_mesh.pyx:426(__get__)
```

This PR:
```
         19766522 function calls (19720360 primitive calls) in 48.857 seconds

   Ordered by: internal time
   List reduced from 1312 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       51    6.270    0.123    6.297    0.123 _triangle_mesh.pyx:445(__get__)
       51    4.994    0.098    5.006    0.098 _triangle_mesh.pyx:426(__get__)
       49    4.172    0.085    6.196    0.126 _triangle_mesh.pyx:1904(regularize)
   399026    2.999    0.000    3.960    0.000 _triangle_mesh.pyx:910(edge_collapse)
   354090    2.755    0.000    7.397    0.000 _triangle_mesh.pyx:1442(edge_split)
17956/12627    2.607    0.000    3.614    0.000 dual_marching_cubes.py:673(vert_proc)
        5    2.047    0.409   13.721    2.744 _triangle_mesh.pyx:1965(relax)
        1    2.027    2.027    2.079    2.079 _triangle_mesh.pyx:524(_initialize_halfedges)
   633022    1.995    0.000    1.995    0.000 _triangle_mesh.pyx:1628(edge_flip)
   354090    1.937    0.000    2.091    0.000 _triangle_mesh.pyx:1406(_new_vertex)
    84961    1.872    0.000    1.957    0.000 {method 'fix_empty_nodes' of 'PYME.experimental._octree.Octree' objects}
  2124540    1.204    0.000    1.794    0.000 _triangle_mesh.pyx:1330(_insert_new_edge)
   179665    0.844    0.000    0.844    0.000 {method 'reduce' of 'numpy.ufunc' objects}
    26860    0.821    0.000    2.729    0.000 dual_marching_cubes.py:175(<listcomp>)
   219186    0.813    0.000    0.813    0.000 {built-in method numpy.array}
      237    0.755    0.003    0.755    0.003 {method 'sort' of 'numpy.ndarray' objects}
       12    0.691    0.058    0.691    0.058 {method 'argsort' of 'numpy.ndarray' objects}
   161160    0.690    0.000    1.942    0.000 dual_marching_cubes.py:140(subdivided)
  3186810    0.629    0.000    0.736    0.000 _triangle_mesh.pyx:1245(_get_insertion_slot)
       51    0.487    0.010    6.791    0.133 _triangle_mesh.pyx:455(__get__)
```

**Comment by David-Baddeley** [comment]
I don't think you can make that abs -> square substitution and keep the maths the same - it would be fine if the `abs()` was around the outside of the sum, but because it's a sum of abs()s I don't think it will be OK.

suspect the issue here is that it's calling the python abs function, rather than c `abs()` from stdlib (which the compiler should make short work of)

**Comment by David-Baddeley** [comment]
You should be able to see in the generated code which `abs` it ends up calling - `PyNumber_Absolute` or something similar is what you need to look for (bad)

**Comment by David-Baddeley** [comment]
if it's calling a proper abs, then the speed improvement is likely due to avoiding splits/collapses that ti would normally do rather than any actual speed improvement.

**Comment by David-Baddeley** [comment]
looking at an old version, it definitely used `PyNumber_Absolute` ...

image

**Comment by zacsimile** [comment]
Yep, |x| -> x^2 won't work since it's a sum of x^2 terms. I got too excited.

I'd love to switch to C version of `abs()`. Do you know how to force cython to do this during compilation? I figured it would do so automatically, but it seems not.

**Comment by David-Baddeley** [comment]
changing the type definition to `int` from `np.int_32t` at the top of the function fixes it cython uses the stdlib abs instead ...

**Comment by David-Baddeley** [comment]
image


now if only we could get rid of that `if(unlikely(....)` stuff

**Comment by zacsimile** [comment]
Switched to `int` to force c abs, still a nice improvement.

```
         19751451 function calls (19705289 primitive calls) in 51.707 seconds

   Ordered by: internal time
   List reduced from 1312 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       51    6.079    0.119    6.107    0.120 _triangle_mesh.pyx:445(__get__)
       51    4.974    0.098    4.985    0.098 _triangle_mesh.pyx:426(__get__)
       47    4.794    0.102    6.128    0.130 _triangle_mesh.pyx:1904(regularize)
   407158    3.201    0.000    4.160    0.000 _triangle_mesh.pyx:910(edge_collapse)
17956/12627    3.042    0.000    4.263    0.000 dual_marching_cubes.py:673(vert_proc)
   359431    3.021    0.000    8.236    0.000 _triangle_mesh.pyx:1442(edge_split)
        1    2.424    2.424    2.482    2.482 _triangle_mesh.pyx:524(_initialize_halfedges)
    84961    2.252    0.000    2.352    0.000 {method 'fix_empty_nodes' of 'PYME.experimental._octree.Octree' objects}
   359431    2.232    0.000    2.411    0.000 _triangle_mesh.pyx:1406(_new_vertex)
        5    2.019    0.404   13.465    2.693 _triangle_mesh.pyx:1964(relax)
  2156586    1.333    0.000    1.986    0.000 _triangle_mesh.pyx:1330(_insert_new_edge)
   382236    1.303    0.000    1.303    0.000 _triangle_mesh.pyx:1628(edge_flip)
   179665    0.998    0.000    0.998    0.000 {method 'reduce' of 'numpy.ufunc' objects}
    26860    0.965    0.000    3.256    0.000 dual_marching_cubes.py:175(<listcomp>)
       12    0.841    0.070    0.841    0.070 {method 'argsort' of 'numpy.ndarray' objects}
   219186    0.836    0.000    0.836    0.000 {built-in method numpy.array}
   161160    0.801    0.000    2.309    0.000 dual_marching_cubes.py:140(subdivided)
      237    0.777    0.003    0.777    0.003 {method 'sort' of 'numpy.ndarray' objects}
  3234879    0.723    0.000    0.845    0.000 _triangle_mesh.pyx:1245(_get_insertion_slot)
   718862    0.505    0.000    0.741    0.000 _triangle_mesh.pyx:1375(_new_face)
```

**Comment by zacsimile** [comment]
How did you visualize the C calls?

**Comment by David-Baddeley** [comment]
the .html output is automatically generated when you run `cython` (tecnically it's the -a command line option - i.e. `cython -a myfile.pyx`), but for some reason I don't need to specify the -a on my machine.

**Comment by David-Baddeley** [comment]
It's super useful, as it highlights any line which results in a python call.

**Comment by zacsimile** [comment]
Ah cool, thanks!

**Comment by David-Baddeley** [comment]
Looking at the profile, my next targets would probably be `face_normals` and `vertex_neighbours`. 

There looks to be a lot we could do here - low hanging fruit would be to just keep a boolean flag for, e.g. `_face_normals_valid` and invalidate this rather than always doing the `np.all(...)` check, but we could probably also look at making `c_update_face_normals` accept something other than a python list.

**Comment by zacsimile** [comment]
Yeah those are both good ideas. The boolean certainly could be implemented quite quickly and would help a bit. Maybe a `c_update_all_face_normals()` function instead of eliminating the ability to past a list of indices?

**Comment by zacsimile** [comment]
I added the flags. I didn't see any noticeable improvements but maybe eliminating the list will help.

I actually don't see `face_normals` or `vertex_neighbors` showing up high in the profile. What are you sorting by?

**Comment by David-Baddeley** [comment]
They're the top two lines ....

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       51    6.079    0.119    6.107    0.120 _triangle_mesh.pyx:445(__get__)
       51    4.974    0.098    4.985    0.098 _triangle_mesh.pyx:426(__get__)
```

**Comment by David-Baddeley** [comment]
shows up as `__get__` as they're properties

**Comment by zacsimile** [comment]
Ohh I didn't realize those were the get calls. Got it.

**Comment by zacsimile** [comment]
Some marginal gains, but getting better.

```
         19726885 function calls (19680723 primitive calls) in 47.360 seconds

   Ordered by: internal time
   List reduced from 1312 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       49    5.014    0.102    6.392    0.130 _triangle_mesh.pyx:1910(regularize)
       51    4.540    0.089    4.540    0.089 _triangle_mesh.pyx:449(__get__)
   406723    3.255    0.000    4.182    0.000 _triangle_mesh.pyx:916(edge_collapse)
   358879    3.241    0.000    8.463    0.000 _triangle_mesh.pyx:1448(edge_split)
17956/12627    3.068    0.000    4.233    0.000 dual_marching_cubes.py:673(vert_proc)
   358879    2.277    0.000    2.450    0.000 _triangle_mesh.pyx:1412(_new_vertex)
        1    2.208    2.208    2.261    2.261 _triangle_mesh.pyx:528(_initialize_halfedges)
    84961    2.159    0.000    2.251    0.000 {method 'fix_empty_nodes' of 'PYME.experimental._octree.Octree' objects}
       51    2.116    0.041    2.116    0.041 _triangle_mesh.pyx:428(__get__)
        5    1.676    0.335    8.247    1.649 _triangle_mesh.pyx:1970(relax)
   381599    1.353    0.000    1.353    0.000 _triangle_mesh.pyx:1634(edge_flip)
  2153274    1.273    0.000    1.891    0.000 _triangle_mesh.pyx:1336(_insert_new_edge)
    26860    1.023    0.000    3.234    0.000 dual_marching_cubes.py:175(<listcomp>)
   179512    0.969    0.000    0.969    0.000 {method 'reduce' of 'numpy.ufunc' objects}
   219186    0.935    0.000    0.935    0.000 {built-in method numpy.array}
      237    0.861    0.004    0.861    0.004 {method 'sort' of 'numpy.ndarray' objects}
   161160    0.809    0.000    2.307    0.000 dual_marching_cubes.py:140(subdivided)
       12    0.779    0.065    0.779    0.065 {method 'argsort' of 'numpy.ndarray' objects}
  3229911    0.687    0.000    0.806    0.000 _triangle_mesh.pyx:1251(_get_insertion_slot)
   717758    0.557    0.000    0.801    0.000 _triangle_mesh.pyx:1381(_new_face)
```

**Pull request merged**
