### PR TITLE
timeout poll loop in rule pushing

### PR DESCRIPTION
**Pull request by barentine**
Addresses issue #if something goes wrong our rule threads keep checking if a datasource is complete/rule is complete forever.

**Is this a bugfix or an enhancement?**
sure
**Proposed changes:**
- if e.g. an events file never makes it, eventually raise an error in the rule pushing thread and give up rather than continuing and burdening clusterIO/PYMEAcquire indefinitely
- remove the 1.5 s wait as mentioned in the TODO

**Checklist:**
- [x] tested on scope
- [ ] Tested with numpy=1.14
- [ ] Tested on python 2.7 and 3.6
- [ ] Tested with wx=3.x and wx=4.x [if UI code]
- [ ] Does the PR avoid variable renaming in existing code, whitespace changes, and other forms of tidying? [There is a place for code tidying, but it makes reviewing 
much simpler if this is kept separate from functional changes]

If an enhancement (or non-trivial bugfix):

- [ ] Has this been discussed in advance (feature request, PR proposal, email, or direct conversation)?
- [ ] Does this change how users interact with the software? How will these changes be communicated?
- [ ] Does this maintain backwards compatibility with old data?
- [ ] Does this change the required dependencies?
- [ ] Are there any other side effects of the change?

### CODE REVIEW

**Comment by David-Baddeley** [comment]
If we do have a default timeout, I'd want it to be rather more conservative - at least several minutes. That said, I'm not convinced a timeout is desirable, especially in the base Rule class. 

I'd want to be convinced that a) this solves a pressing need and b) this is the most sensible way to solve that. 

Examples where you'd run into issues with a short timeout are a little constructed at present, but could include, e.g. pushing 3D frames (rather than 2D), and having a single rule process e.g. the results of multiple analyses. It does feel, however, that we could be introducing an additional constraint that has the potential to bite us later. If we were to e.g. put tile reconstruction into rules, I could potentially see us hitting this constraint.

**Comment by David-Baddeley** [comment]
For the specific PYMEAcquire problem, I suspect it would be better to subclass `LocalizationRule` with a version which looked to the spooler rather than the cluster to determine if a series was complete.

**Comment by barentine** [comment]
on the one hand having a timeout as argument means you _could_ change it, but I think you're right that subclassing LocalizationRule would be smartest and additionally be more performant to `lambda : self.spooler.spool_complete` than clusterIO grep for the events file.

**Comment by barentine** [comment]
going to alternative fix with the spoollocal rule

**Pull request closed without merging**
