### PR TITLE
Unifying event name and description types

### PR DESCRIPTION
**Pull request by barentine**
Events ordering and format are at the moment inconsistent in that when events are passed as a structured array they're in a different order than when they're written to json as list. Additionally, because the `S` dtypes are loaded as bytes in py3, and `str(b'unfortunate') = "b'unfortunate'"`we get some unnecessary awkwardness which we at the moment carry around when we handle/display events:
image

Since the `Events` tables saved in h5r are structured, we can easily convert them from bytes to unicode and a consistent order with the list upon loading. This is handled in a new file, `PYME.IO.events`, and allows us to drop all the bytes encoding/decoding when we're really after unicode.

This PR should be Python2 compatible
```
$ python
Python 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
>>> t = tables.open_file('/home/smeagol/Desktop/20_2_series_00002_1.h5r')
>>> t.root.Events[:]
array([('PiezoOnTarget', 1.58222555e+09, '48.262'),
       ('PiezoOnTarget', 1.58222555e+09, '48.258'),
       ('PiezoOnTarget', 1.58222555e+09, '48.264'),
       ('PiezoOnTarget', 1.58222555e+09, '48.262'),
       ('PiezoOnTarget', 1.58222555e+09, '48.260'),
       ('PiezoOnTarget', 1.58222555e+09, '48.261'),
       ('PiezoOnTarget', 1.58222555e+09, '48.258'),
       ('PiezoOnTarget', 1.58222555e+09, '48.259'),
       ('PiezoOnTarget', 1.58222555e+09, '48.257'),
       ('PiezoOnTarget', 1.58222555e+09, '48.255'),
       ('PiezoOnTarget', 1.58222555e+09, '48.264'),
       ('PiezoOnTarget', 1.58222555e+09, '48.267'),
       ('PiezoOnTarget', 1.58222555e+09, '48.268'),
       ('PiezoOnTarget', 1.58222555e+09, '48.270'),
       ('PiezoOnTarget', 1.58222555e+09, '48.270'),
       ('PiezoOnTarget', 1.58222555e+09, '48.272'),
       ('PiezoOnTarget', 1.58222555e+09, '48.276'),
       ('PiezoOnTarget', 1.58222555e+09, '48.279'),
       ('PiezoOnTarget', 1.58222555e+09, '48.282'),
       ('PiezoOnTarget', 1.58222555e+09, '48.285'),
       ('PiezoOnTarget', 1.58222555e+09, '48.289'),
       ('PiezoOnTarget', 1.58222555e+09, '48.290'),
       ('PiezoOnTarget', 1.58222555e+09, '48.294'),
       ('PiezoOnTarget', 1.58222555e+09, '48.304'),
       ('ProtocolFocus', 1.58222555e+09, '0, 49.988'),
       ('PiezoOnTarget', 1.58222555e+09, '48.307'),
       ('PiezoOnTarget', 1.58222555e+09, '48.314'),
       ('ProtocolTask', 1.58222555e+09, '1, DisableLock, '),
       ('PiezoOffsetUpdate', 1.58222555e+09, '-1.6720'),
       ('ProtocolFocus', 1.58222555e+09, '801, 51.188'),
       ('PiezoOnTarget', 1.58222555e+09, '49.489'),
       ('ProtocolFocus', 1.58222555e+09, '1601, 52.388'),
       ('PiezoOnTarget', 1.58222555e+09, '50.705'),
       ('ProtocolFocus', 1.58222555e+09, '2401, 53.588'),
       ('PiezoOnTarget', 1.58222555e+09, '51.883'),
       ('ProtocolFocus', 1.58222555e+09, '3201, 54.188'),
       ('PiezoOnTarget', 1.58222555e+09, '52.505'),
       ('ProtocolFocus', 1.58222555e+09, '4001, 52.988'),
       ('PiezoOnTarget', 1.58222555e+09, '51.289'),
       ('ProtocolFocus', 1.58222555e+09, '4801, 51.788'),
       ('PiezoOnTarget', 1.58222555e+09, '50.087'),
       ('ProtocolFocus', 1.58222555e+09, '5601, 50.588'),
       ('PiezoOnTarget', 1.58222555e+09, '48.885'),
       ('ProtocolFocus', 1.58222556e+09, '6401, 49.988'),
       ('PiezoOnTarget', 1.58222556e+09, '48.304'),
       ('PiezoOnTarget', 1.58222556e+09, '48.305'),
       ('ProtocolTask', 1.58222556e+09, 'EnableLock, '),
       ('ProtocolTask', 1.58222556e+09, 'LaunchAnalysis, ')],
      dtype=[('EventName', 'S32'), ('Time', '<f8'), ('EventDescr', 'S256')])
>>> t.root.Events[:].astype([('EventName', 'U32'), ('Time', '<f8'), ('EventDescr', 'U256')])
array([(u'PiezoOnTarget', 1.58222555e+09, u'48.262'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.258'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.264'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.262'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.260'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.261'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.258'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.259'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.257'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.255'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.264'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.267'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.268'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.270'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.270'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.272'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.276'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.279'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.282'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.285'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.289'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.290'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.294'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.304'),
       (u'ProtocolFocus', 1.58222555e+09, u'0, 49.988'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.307'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.314'),
       (u'ProtocolTask', 1.58222555e+09, u'1, DisableLock, '),
       (u'PiezoOffsetUpdate', 1.58222555e+09, u'-1.6720'),
       (u'ProtocolFocus', 1.58222555e+09, u'801, 51.188'),
       (u'PiezoOnTarget', 1.58222555e+09, u'49.489'),
       (u'ProtocolFocus', 1.58222555e+09, u'1601, 52.388'),
       (u'PiezoOnTarget', 1.58222555e+09, u'50.705'),
       (u'ProtocolFocus', 1.58222555e+09, u'2401, 53.588'),
       (u'PiezoOnTarget', 1.58222555e+09, u'51.883'),
       (u'ProtocolFocus', 1.58222555e+09, u'3201, 54.188'),
       (u'PiezoOnTarget', 1.58222555e+09, u'52.505'),
       (u'ProtocolFocus', 1.58222555e+09, u'4001, 52.988'),
       (u'PiezoOnTarget', 1.58222555e+09, u'51.289'),
       (u'ProtocolFocus', 1.58222555e+09, u'4801, 51.788'),
       (u'PiezoOnTarget', 1.58222555e+09, u'50.087'),
       (u'ProtocolFocus', 1.58222555e+09, u'5601, 50.588'),
       (u'PiezoOnTarget', 1.58222555e+09, u'48.885'),
       (u'ProtocolFocus', 1.58222556e+09, u'6401, 49.988'),
       (u'PiezoOnTarget', 1.58222556e+09, u'48.304'),
       (u'PiezoOnTarget', 1.58222556e+09, u'48.305'),
       (u'ProtocolTask', 1.58222556e+09, u'EnableLock, '),
       (u'ProtocolTask', 1.58222556e+09, u'LaunchAnalysis, ')],
      dtype=[('EventName', '<U32'), ('Time', '<f8'), ('EventDescr', '<U256')])
>>> u'ProtocolTask' == 'ProtocolTask'
True
>>> u'ProtocolTask' == b'ProtocolTask'
True
```

### CODE REVIEW

**Comment by David-Baddeley** [comment]
Will have to think about this a bit - I'm of the opinion that anything on disk / on the network should be bytes / c strings rather than unicode (much less to go wrong, and gives us a much better chance of e.g. opening our HDF files elsewhere - e.g. Matlab, c, java etc ...). 

Basically python3 has really dropped the ball with how hard it makes to compare bytes and strings. Options which would be more acceptable to me are:
- use a custom function to compare strings, which doesn't care if they are bytes or not e.g. `compare('string', b'string') == True` (it's quite possible that such a function already exists in, e.g. `six`)
- use a custom function to cast to string which handles bytes sensibly. The fact that `str(b'string')` returns `"b'string'"` is an incredibly bad design choice and runs against all python norms (python has `repr()` for this exact purpose and in a normal world you'd expect `repr(b'string') == "b'string'"` and `str(b'string') == 'string'` )

**Comment by David-Baddeley** [comment]
`six` has the latter custom cast, as `six.ensure_str()`

**Comment by barentine** [comment]
I'm of the opinion we should just be good sports and write as close to normal python 3 code as possible. Six should be for smoothing over a migration, not for hiding from python 3 data types forever.

**Comment by barentine** [comment]
I agree that we should save / send bytes rather than unicode, but I think once we load it into python it's not crazy to cast things we intend to use as (python 3) str to str.

**Comment by David-Baddeley** [comment]
I think most of the events stuff has been covered in subsequent changes, closing

**Pull request closed without merging**
