### PR TITLE
Add metadata to Octree and TriangleMesh and associated recipes

### PR DESCRIPTION
**Pull request by zacsimile**
Metadata handlers for `Octree` and `TriangleMesh` allow us to add recipe metadata as well.

### CODE REVIEW

**Comment by David-Baddeley** [comment]
- should really bring sample metadata through from the image / points used to create the surfaces (basically just inherit the metadata of the input data)

- I think all the metadata added here should be under the `Processing.` top level key (it's not quite as clear cut as for most recipe modules, as there is a pronounced change in data format, but still probably best).

**Comment by zacsimile** [comment]
Sounds good. Could you update or rewrite this to pass the metadata as you prefer?

**Comment by David-Baddeley** [comment]
I've taken a very different tack in #1288 which tries to achieve the same thing, but with much less boilerplate. With any luck, this will form the basis of all the metadata stuff being handled more or less automatically.

**Comment by David-Baddeley** [comment]
superseeded by https://github.com/python-microscopy/python-microscopy/pull/1288

**Pull request closed without merging**
