### PR TITLE
add transactional recipe module addition

### PR DESCRIPTION
**Pull request by David-Baddeley**
Addresses issue #525 .

**Is this a bugfix or an enhancement?**

Bit of both. 

**Proposed changes:**

Add a backend giving a transactional way of adding recipe modules. Partial solution to #525 (which also requires plugins to be modified to use this)

### CODE REVIEW

**Comment by David-Baddeley** [comment]
extras now modified too ...

**Comment by zacsimile** [comment]
Confirmed via user testing this works on python 3.6.10/macOS 10.15.7/numpy 1.16.6/wxpython 4.0.4.

**Comment by David-Baddeley** [comment]
@barentine - this hits the multiview shiftmap calibration (specifically the results now don't get saved in the recipe namespace, only to disk). I can't see this being an issue, but would be great if you could have a quick look before I merge. 

I've also changed the calling pattern on some of the other multi-view modules (configure, then add, rather than disable invalidation, add, configure, re-enable invalidation) as a) this is a cleaner pattern and b) avoids having to manually roll-back if a user cancels the dialog. There is a chance that some of the `configure_traits()` calls should be swapped for `edit_no_invalidate()` calls as well.

**Comment by barentine** [comment]
Hi @David-Baddeley thanks for pointing that out. All looks good to me - have not tested it as of yet, but will be sure to tomorrow and will PR any tweaks if necessary. Quick notes:
- I like that we're taking the shiftmap out of the recipe namespace in the calibration
- the calibrate shifts and map astigmatism were both calling `configure_traits` on the `ModuleCollection` rather than an individual modules - that was to allow editing of filters, back before we had the data pipeline view.
- related to the last point, we can almost certainly drop the visframe refresh on new line 395 in multiviewMapping
- I would appreciate us actually deleting the old style disable invalidation, configure, re-enable stuff, rather than just commenting it out - no reason to muddy the file

**Comment by barentine** [comment]
Running into an issue with `pipeline_view_min` missing the 'OK' button
image

**Comment by barentine** [comment]
problem exists with `pipeline_view` as well (unsurprising)

**Comment by barentine** [comment]
Note that the default view, i.e.
`if not calibration_module.configure_traits(kind='modal'):`
works fine

**Comment by David-Baddeley** [comment]
This is roughly how the pipeline view is supposed to work - condensed, no buttons on individual modules. Where are you running into this?

**Comment by barentine** [comment]
would you mind documenting that in `recipes.base.ModuleBase` and `ModuleCollection` @David-Baddeley? As I understand it the `pipeline_view` of a module shouldn't be configured directly in modal (or you won't get an OK / cancel), but is really just there for the `ModuleCollection` configure?

I hit it in `PYME/LMVis/Extras/multiviewMapping.py` and will PR the change

**Comment by David-Baddeley** [comment]
Yep - adding the appropriate docs would be a good idea. The pipeline view
is just there for when you want to configure the whole pipeline in one go
(and the vertical display in PYMEVis).

**Pull request merged**
