### PR TITLE
Splitter tidying

### PR DESCRIPTION
**Pull request by David-Baddeley**
Remove some duplicated un-splitting code, fix 1 based indexing, WIP and currently untested

### CODE REVIEW

**Comment by csoeller** [comment]
Excellent. I will keep looking at that and see if it provides the leads that I probably need.

Just a very quick impression in trying to test the PYME.localization.splitting.get_splitter_rois() function as a way to see how that might work. I have used it to implement a modified `Unmix` function and use the `rois` option to the splitter. At least the unmix results seemed quite highly dependent on the ROI chosen even in so far as lining up the relevant sections of the ‘red’ and ‘green’  sections seemed to change in not quite expected ways…

```python
@init_gui('splitter')
def ini_splitter(MainFrame,scope):
    from PYME.Acquire.Hardware import splitter
    constrainwidth = 550 # we constrain the width of the ROI region to 550 pixels; maximum is 1024 for the whole width
    chipheight = scope.camera['Zyla'].GetCCDHeight()
    chipwidth = scope.cameras['Zyla'].GetCCDWidth()
    chipwidth_h = int(chipwidth/2) # do we need to check for non-even width?
    borderwidth = int(int(chipwidth/2)-constrainwidth) # border size to leave on the left and on the right side
    scope.splt = splitter.Splitter(MainFrame, scope, scope.cameras['Zyla'],
                                   flipChan = 0, dichroic = 'BS50-50',
                                   transLocOnCamera = 'Left', flip=False,
                                   dir='left_right', constrain=False, border=0,
                                   # ROI format x1,y1,x2,y2 with x2, y2 EXCLUDED from the ROI
                                   rois = [[borderwidth,0,chipwidth_h,chipheight],
                                           [chipwidth_h,0,chipwidth-borderwidth,chipheight]])
```

And using this unmix implementation:

    def Unmix_roi(self, data, mixMatrix, offset):
        from PYME.localisation.splitting import split_image
        import scipy.linalg
        umm = scipy.linalg.inv(mixMatrix)

        dsa = data.squeeze() - offset
        
        split_im = split_image(self.mdh, dsa)

        g_ = split_im[:,:,0].squeeze()
        r_ = split_im[:,:,1].squeeze()
        g = umm[0,0]*g_ + umm[0,1]*r_
        r = umm[1,0]*g_ + umm[1,1]*r_

        return [r.reshape(r.shape + (1,)),g.reshape(r.shape + (1,))]

I'll keep checking what is going on...

**Comment by David-Baddeley** [comment]
the `split_image` implementation in `localization.splitting` is definitely broken. It's not actually used anywhere in the code at present, and suspect it was an earlier incomplete refactoring.

**Comment by David-Baddeley** [comment]
Added some test cases and docs. Tests can be run using

`pytest tests/PYME/localization/test_splitting.py`

**Comment by csoeller** [comment]
@David-Baddeley , the work on this is definitely appreciated.

One thing that is still a little unclear to me is why you added the new function `get_channel` to `PYME.analysis.splitting` that is *not* using the logic in `PYME.localization.splitting.get_splitter_rois()`. Similarly, the setting up of the unsplit datasource could also use this function, it seems to me. Is there a clear reason why this should not be done?

Currently, the separate logic of figuring out ROIs in the various places seems to me the most confusing and error prone part of the implementation. I hope I am not overlooking obvious explanations.

**Comment by David-Baddeley** [comment]
agreed ... it still needs to be collapsed further to remove duplication between `get_channel` and `get_splitter_rois`. I was just taking it one step at a time removing duplication between `UnsplitDataSource` and the `Unmixer` class before putting them onto a common basis with the localization code - there is rather a lot to unwind in terms of differences. To be able to be used in `UnsplitDataSource`, `get_splitter_rois` still needs to be modified to support more than 2 channels.

**Comment by csoeller** [comment]
Ok, all good, happy to see that I am broadly understanding the issues now a bit better. Happy with whatever speed is reasonable to eventually get to a central place where the main logic lives. We'll keep testing with our setup the bits that matter most to us, currently the live unmixing (for splitter alignment) and the eventual localisation analysis. The `UnsplitDataSource` is a bit lower priority but relatively easy to test with existing datasets.

**Comment by David-Baddeley** [comment]
`UnsplitDataSource` is also used for the live unmixing (at least now after refactoring).

**Comment by csoeller** [comment]
In that case it should be possible to test functionality with the `Processing>Unsplit` menu function as a means to test the unmix functionality. As it is I still get errors for what I think should be well working ROI and splitter configs. I have created a temporary repo to share some example data files for testing. Currently contains [28_11_series_B-extracted.h5](https://github.com/csoeller/PYME-splitter-example-data/blob/main/28_11_series_B-extracted.h5) which causes an error:

```
  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/DSView/scrolledImagePanel.py", line 60, in OnPaint

    self.renderer(MemDC)

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/DSView/arrayViewPanel.py", line 444, in _do_paint

    im = self._render(fullImage)

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/DSView/arrayViewPanel.py", line 983, in _render

    seg = ds[slice_key +  (chan,)].squeeze().T

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/IO/DataSources/BaseDataSource.py", line 346, in __getitem__

    out[:, :, zi, ci, ti] = self.getSlice(slice_idx)[keys[0], keys[1]]

ValueError: could not broadcast input array from shape (292,438) into shape (272,438)
```

**Comment by csoeller** [comment]
Added a couple more example files and info in [README](https://github.com/csoeller/PYME-splitter-example-data/blob/main/README.md) to [PYME-splitter-example-data](https://github.com/csoeller/PYME-splitter-example-data/tree/main).

**Comment by csoeller** [comment]
I am not sure how one can best collaborate on this PR. I have tested a number of small patches that make the splitter stuff in this branch work ok with all the data that we have so far.

The first change should not be controversial, it just supplies the missing `rois` argument for the unmixer creation. Without it, the live `Unmix` functionality does not work for anything but the "default" case (e.g. split in dir top_down is used regardless of splitter settings).

```diff
diff --git a/PYME/Acquire/Hardware/splitter.py b/PYME/Acquire/Hardware/splitter.py
index 8dcd451e8..7ecefa6d4 100644
--- a/PYME/Acquire/Hardware/splitter.py
+++ b/PYME/Acquire/Hardware/splitter.py
@@ -40,9 +40,9 @@ class Splitter:
         self.cam = cam
         self.flipChan=flipChan
         self.parent = parent
-        self.unmixer = splitting.Unmixer(flip=flip, axis = dir)
         self.flip = flip
         self._rois=rois
+        self.unmixer = splitting.Unmixer(flip=flip, axis = dir, chanROIs=self.rois)
 
         #which dichroic mirror is installed
         self.dichroic = dichroic
```

The second patch component (two files) demonstrates how one can use the the existing `PYME.localization.splittingget_splitter_rois()` so that the UnsplitDataSource works as expected for the test cases that I have provided. This can either use a prepopulated `mdh` (e.g. from `self.image.mdh`) or populates one from the arguments provided. I have tried both cases and both work for the 2 chanROIs cases tested so far.

I am sure one can discuss if this is the right way to do it but it does demonstrate that fixing the width and height determination of the channels ROIs are the crucial things to make this work.

```diff
diff --git a/PYME/DSView/modules/splitter.py b/PYME/DSView/modules/splitter.py
index 604ad13a4..9ceef28dc 100644
--- a/PYME/DSView/modules/splitter.py
+++ b/PYME/DSView/modules/splitter.py
@@ -105,8 +105,10 @@ class Unmixer(Plugin):
 
         usds = [UnsplitDataSource.DataSource(self.image.data,
                                              [ROIX1, ROIY1, ROIX2, ROIY2],
-                                             i, flip, sf, chanROIs=chanROIs, voxelsize=self.image.voxelsize) for i in
-                range(numROIs)]
+                                             i, flip, sf, chanROIs=chanROIs,^M
+                                             voxelsize=self.image.voxelsize,^M
+                                             mdh=None)^M
+                for i in range(numROIs)]^M
 
         return usds
 
diff --git a/PYME/IO/DataSources/UnsplitDataSource.py b/PYME/IO/DataSources/UnsplitDataSource.py
index 209006aaa..7cbeabc96 100644
--- a/PYME/IO/DataSources/UnsplitDataSource.py
+++ b/PYME/IO/DataSources/UnsplitDataSource.py
@@ -21,13 +21,17 @@
 ##################
 from __future__ import print_function
 import numpy as np
+import logging
 from .BaseDataSource import XYTCDataSource
 
 from PYME.localization import splitting
 
+logger = logging.getLogger(__name__)
+
 class DataSource(XYTCDataSource):
     moduleName = 'UnsplitDataSource'
-    def __init__(self,dataSource, ROI, chan=0, flip=True, shiftfield=None, voxelsize=(70., 70., 200.), chanROIs=None):
+    def __init__(self,dataSource, ROI, chan=0, flip=True, shiftfield=None, voxelsize=(70., 70., 200.), chanROIs=None,
+                 mdh=None):
         #self.unmixer = unmixer
         self.dataSource = dataSource
         self.sliceShape = list(self.dataSource.shape[:-1])
@@ -37,12 +41,38 @@ class DataSource(XYTCDataSource):
         self.sliceShape[1] = int(self.sliceShape[1] / 2)
         
         if not chanROIs is None:
-            x, y, w, h = chanROIs[0]
-            #self.sliceShape = [min(self.dataSource.shape[0], w), min(self.dataSource.shape[1], h)]
+            if len(chanROIs) == 2:
+                if mdh is None:
+                    logger.debug("making MetaDataHandler dummy")
+                    from PYME.IO import MetaDataHandler
+                    mdh = MetaDataHandler.DictMDHandler()
+                    mdh['Camera.ROIOriginX'] = ROI[0]
+                    mdh['Camera.ROIOriginY'] = ROI[1]
+                    mdh['Camera.ROIWidth'] = ROI[2]-ROI[0]
+                    mdh['Camera.ROIHeight'] = ROI[3]-ROI[1]
+                    mdh['Splitter.Channel0ROI'] = chanROIs[0]
+                    mdh['Splitter.Channel1ROI'] = chanROIs[1]
+                    mdh['Splitter.Flip'] = flip
+                else:
+                    logger.debug("using supplied MetaDataHandler")
+                xgs, xrs, ygs, yrs = splitting.get_splitter_rois(mdh,self.dataSource.shape[:2])
+                wg = (xgs.stop - xgs.start) // xgs.step
+                hg = (ygs.stop - ygs.start) // ygs.step
+
+                wr = (xrs.stop - xrs.start) // xrs.step
+                hr = (yrs.stop - yrs.start) // yrs.step
+
+                w = min(wg,wr)
+                h = min(hg,hr)
+            else:
+                # this version of the code is definitely broken for some 2 channel splitter configs,
+                # not sure about MultiView with numROIs > 2, for which this codepath will be used
+                x, y, w, h = chanROIs[0]
+                #self.sliceShape = [min(self.dataSource.shape[0], w), min(self.dataSource.shape[1], h)]
             
-            for x_, y_, w_, h_ in chanROIs:
-                w = min(self._raw_w - x_, w)
-                h = min(self._raw_h - y_, h)
+                for x_, y_, w_, h_ in chanROIs:
+                    w = min(self._raw_w - x_, w)
+                    h = min(self._raw_h - y_, h)
                 
             self.sliceShape = [w, h]
```

**Comment by David-Baddeley** [comment]
Sorry I've taken so long to get to this - the couple of weeks pre Christmas turned out to be hectic and only just getting back to things. First change is definitely uncontentious. 

I don't really like the second one though, and have had a go at an alternative ... (see latest commits). This should go a long way towards parsing all the info in a single place (the one exception is for live acquisition for which there is no metadata - and the ROI could potentially change underneath us). Could still use a little tidying, and a lot of testing but think it's slowly getting there.

**Comment by csoeller** [comment]
Thanks @David-Baddeley, much appreciated and time constraints are fully understood. If you don't mind I suggest we trysome local testing with actual hardware before merging into master for good. That way we can be a bit more certain that things work as expected. We can start testing beginning of next week.

**Comment by David-Baddeley** [comment]
Testing would be very much appreciated! There's a lot that has changed ...

**Comment by csoeller** [comment]
We carried out some first testing and needed a few smallish tweaks to get live unmixing working properly.

I wasn't sure how to add this directly to the PR. As a stopgap, you can access the commit via my fork of pyme, see [this commit](https://github.com/csoeller/python-microscopy/commit/9b73e034ebd659e1b78bb1d98782bc0c7e8ce283).

**Pull request merged**
