### PR TITLE
onTarget tolerance adjustment in piezo init

### PR DESCRIPTION
**Pull request by zacsimile**
Make it possible to change the `onTarget` tolerance on piezo initialization. Needed for my less precise piezo.

Might be worth thinking about refactoring the piezo hardware code. I think this, along with many other parameters, belongs in the `BasePizeo` class, but perhaps I am wrong.

### CODE REVIEW

**Comment by David-Baddeley** [comment]
`target_tolerance` does not belong in the base class, as we would hope that piezo drivers provide there own, non-blocking, low-latency, hardware ,`on_target()` functionality (i.e. this is a hack to work around the non-ideal behaviour of a particular piezo controller). I could however see an argument for having a specific threaded piezo base class as I suspect the problems the threaded class works around will not be that unusual.

In terms of refactoring, we

**Comment by zacsimile** [comment]
Hi @David-Baddeley. It looks like you were cut off mid-thought

**Comment by David-Baddeley** [comment]
I think that belonged at the beginning of the previous sentence ...

**Comment by zacsimile** [comment]
Ah, got it. Your comments make sense. Do you have an issue with how I've implemented this `targetTolerance` here? Or is this OK?

**Pull request merged**
