### PR TITLE
make sure ruleserver.html gets distributed with packages

### PR DESCRIPTION
**Pull request by barentine**
Addresses issue: Running `PYMERuleServer` on a conda installation currently fails because the ruleserver.html isn't included in package data
```
$ PYMERuleServer
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/PYME/cluster/ruleserver.py", line 830, in run
    self.distributor = WFRuleServer(self.port, bind_addr=self.bind_addr)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/PYME/cluster/ruleserver.py", line 772, in __init__
    RuleServer.__init__(self)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/PYME/cluster/ruleserver.py", line 440, in __init__
    with open(os.path.splitext(__file__)[0] + '.html', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/miniconda3/lib/python3.6/site-packages/PYME/cluster/ruleserver.html'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/PYMERuleServer", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/PYME/cluster/PYMERuleServer.py", line 79, in main
    sa = proc.distributor.socket.getsockname()
AttributeError: 'ServerThread' object has no attribute 'distributor'
```

**Is this a bugfix or an enhancement?**
bugfix
**Proposed changes:**
- swap add 'cluster' directory as data directory in sepuptools rather than downstream 'cluster/clusterUI'. Alternatively we could move rulerserver.html?

**Checklist:**
- [x] tested

```
$ python setup.py sdist
$ tar tfz dist/python-microscopy-20.7.10.tar.gz | grep ruleserver
python-microscopy-20.7.10/PYME/cluster/ruleserver.py
python-microscopy-20.7.10/PYME/cluster/ruleserver.html
```
- [ ] Tested with numpy=1.14
- [ ] Tested on python 2.7 and 3.6
- [ ] Tested with wx=3.x and wx=4.x [if UI code]
- [x] Does the PR avoid variable renaming in existing code, whitespace changes, and other forms of tidying? [There is a place for code tidying, but it makes reviewing 
much simpler if this is kept separate from functional changes]

If an enhancement (or non-trivial bugfix):

- [ ] Has this been discussed in advance (feature request, PR proposal, email, or direct conversation)?
- [ ] Does this change how users interact with the software? How will these changes be communicated?
- [x] Does this maintain backwards compatibility with old data?
- [ ] Does this change the required dependencies?
- [ ] Are there any other side effects of the change?

### CODE REVIEW

**Comment by David-Baddeley** [comment]
unfortunately we will need to move `ruleserver.html` to a directory without python code and then add that (adding a directory with code as a data dir is problematic).

**Comment by barentine** [comment]
Thanks @David-Baddeley. Reverted the data dir to clusterUI, moved ruleserver.html there, tested ruleserver and setup.py sdist again and should be good to go.

**Comment by David-Baddeley** [comment]
I'm a bit worried that dumping it in clusterUI will cause issues in the future (adding clusterUI as a datadir is a bit of a hack, and might well change in the future).

I'm going to move it to `PYME.resources.web` instead. It's currently still a work in progress, but the aim is to dump all our non code stuff in `PYME.resources` eventually.

**Comment by David-Baddeley** [comment]
Alternative solution merged in 0e5fcc7aa5bf4d3e28cd1110c230b42288ec9481

**Pull request closed without merging**
