### PR TITLE
ueye updates

### PR DESCRIPTION
**Pull request by barentine**
Addresses issue was no GetSerialNumber, raised error if you tried to snapshot

**Is this a bugfix or an enhancement?**
both

**Proposed changes:**

**Checklist:**

- [ ] Tested with numpy=1.14
- [ ] Tested on python 2.7 and 3.6
- [ ] Tested with wx=3.x and wx=4.x [if UI code]
- [ ] Does the PR avoid variable renaming in existing code, whitespace changes, and other forms of tidying? [There is a place for code tidying, but it makes reviewing 
much simpler if this is kept separate from functional changes]

If an enhancement (or non-trivial bugfix):

- [ ] Has this been discussed in advance (feature request, PR proposal, email, or direct conversation)?
- [ ] Does this change how users interact with the software? How will these changes be communicated?
- [ ] Does this maintain backwards compatibility with old data?
- [ ] Does this change the required dependencies?
- [ ] Are there any other side effects of the change?

### CODE REVIEW

**Comment by csoeller** [comment]
Hi @barentine, I have a number of changes in a yet to be submitted PR, that goes a bit further with getting `ueye.py` up to the level of `uc480` module, see the https://github.com/csoeller/python-microscopy/tree/ueye-tweaking branch. Shall we perhaps look into merging our efforts?

**Comment by David-Baddeley** [comment]
@barentine - if Christians changes in #1166 work for you then I'll mark this as a duplicate and close. The only substantive difference is the `IS_RECT()` handling. I'm not really sure what the defining differences here are.

**Comment by csoeller** [comment]
Unless I overlooked something, the difference in the `IS_RECT()` assignments is an additional use of an `ueye.int()` explicit conversion. This may not be needed, I think I picked it up from an example in the `pyueye` docs. Certainly these make explicit that these will be ultimately converted to appropriate ints and performance impact is negligible.

**Comment by David-Baddeley** [comment]
@csoeller - you are correct, I just glanced at the PRs side by side and somehow though there was more of a difference

**Comment by David-Baddeley** [comment]
Duplicate of #1166

**Comment by barentine** [comment]
Yep, sorry for not replying. Thanks both

**Pull request closed without merging**
