### PR TITLE
Make dumbbell test more permissive

### PR DESCRIPTION
**Pull request by zacsimile**
Our tests must pass

### CODE REVIEW

**Comment by David-Baddeley** [comment]
The other way of addressing this which we had talked about was setting the random seed for the fit tests (we also get occasional failures on the other fits, this one is just the most common).

**Comment by zacsimile** [comment]
I remembered, I just wasn't sure exactly what to set when I looked at the code. This is a quick fix. I'm not opposed to the long fix.

**Comment by David-Baddeley** [comment]
was going to try and fix globally, but can't seem to get the tests to fail on my computer. I wonder if it depends on the precise version of pytest (which I think we have pinned in the test setup) and/or if numpy/pytest now does something sneaky with random seeds).

**Comment by David-Baddeley** [comment]
I wonder if it's due to numpy rng changes ...

**Pull request merged**
