### PR TITLE
py3 byte-str fix in clusterUI recipe views

### PR DESCRIPTION
**Pull request by barentine**
bytes.strip(str) fails and there's no reason to encode in the first place since query-dicts should have str keys

### CODE REVIEW

**Comment by David-Baddeley** [comment]
I'm trying to recall why this was `encode()`ed in the first place. Looking back it would seem that  the `encode` is there from the first commit (so pre-dates any py3 work). Only thing I can think of is if django was giving us unicode rather than string.

**Comment by David-Baddeley** [comment]
This is one of the huge annoyances with the 2->3 transition, on py2, encode returns string. 

It's not the dictionary keys we are encoding, it's the values stored at those keys (which may have been unicode).

**Comment by David-Baddeley** [comment]
I suspect that the original `.encode()` was there as a "force this to be a string, whatever it is" to make sure that it had a suitable encoding for use in a URI. URIs are by definition UTF8 encoded c-strings (i.e. 1 byte per character) not unicode (which potentially has a variable number of bytes per character). The more I have to deal with it, the more annoying python3 strings are (in python2, there was a 1:1 mapping between python strings, c strings, and whatever you might write to a file of internet socket, this is unfortunately not the case in py3).

I suspect we could probably merge with no adverse effects, but it makes the code less *safe*.

**Comment by barentine** [comment]
I agree the str/bytes fixes can be annoying, but I think we're mostly done. Re:safe, I suspect very few people using clusterUI recipe views will be running py2. 

Are we all set to merge?

**Comment by David-Baddeley** [comment]
Currently it's around 50:50 for py2/py3 on the recipe views. Will merge with the proviso that we might need to revert if this proves a problem.

**Pull request merged**
