### PR TITLE
Convert channel display to concertina when `DisplayOptionsPanel` in a vertical layout

### PR DESCRIPTION
**Pull request by zacsimile**
Addresses issue #1054.

**Is this a bugfix or an enhancement?**
Enhancement

**Proposed changes:**
- Display channels as concertina of foldable panels when `DisplayOptionsPanel` has a vertical layout

### CODE REVIEW

**Comment by David-Baddeley** [comment]
Will have to pull and have a look at what the GUI looks like. Due to the number of different places this is used I am a little bit cautious about modifying the existing panel rather than developing a new one alongside and substituting in on a case-by case basis. I don't think this caution is necessarily unsurmountable, but there might be a slightly higher threshold than normal to make sure we have this right.

**Comment by David-Baddeley** [comment]
Some visual and sizing improvements to a) bring it closer to the layers GUI and b) make sure that the channels do sensible things when there are too many to show and when windows are resized.

**Comment by David-Baddeley** [comment]
image
image

**Comment by zacsimile** [comment]
Looks good! Thanks, @David-Baddeley!

**Comment by David-Baddeley** [comment]
There is, however, a super odd glitch with the threshold controls showing up in the wrong place until you have expanded the settings panel.
image

Curiously, this doesn't seem to happen to a new image within dh5view

**Comment by zacsimile** [comment]
That is odd. I can't replicate this on my machine. 

```
wxpython                  4.0.4            py37hebc47a7_0  
traits                    6.1.1            py37haf1e3a3_0  
traitsui                  7.1.0                      py_0 
```

Can you give me a step-by-step on how to duplicate this issue?

**Comment by David-Baddeley** [comment]
Open an image on the command line (`dh5view image_name`), or use test data (`dh5view --test3d`). Glitch shows up until you expand "display settings", but goes away when you minimise it again. Does not show up when you create a new image using a command on the processing menu - e.g. processing->Gaussian Filter, or ->Redimension.

Py 3.7, wx 4.04, OSX Big Sur

**Comment by zacsimile** [comment]
Can't replicate it on OSX Catalina (my python/wx are the same as yours). Is it possible this is a Big Sur problem?

**Comment by David-Baddeley** [comment]
Merging, figure we can then commit a fix when we find it

**Comment by David-Baddeley** [comment]
Also checked as working fine fine on MSW

**Pull request merged**
