### PR TITLE
bind arrow-key based scrolling

### PR DESCRIPTION
**Pull request by David-Baddeley**
Addresses issue #669.

**Is this a bugfix or an enhancement?**
Probably best considered a bugfix. Make z/t position update in dsviewer when cursor keys are used with slider.

### CODE REVIEW

**Comment by zacsimile** [comment]
I have to hit `fn` and the up or down arrow key for this to work. left/right keys don't work at all. It's weird that the scroll wheel works when I'm moused over the image but not moused over the slider

**Comment by David-Baddeley** [comment]
On OSX? OSX doesn't support moving sliders with the keyboard / have a concept of slider focus (also doesn't have pgup/pgdown except as bound as fn+arrows). Basically this is win & linux only.

**Comment by David-Baddeley** [comment]
We could try and hack those keys in for OSX, but I'm not sure were we'd have to bind them to get them captured.

**Comment by zacsimile** [comment]
Yeah, on OSX. That's too bad, I'd like this feature on OSX.

**Comment by zacsimile** [comment]
Yeah binding them in the slider itself didn't work when I gave it a go.

**Comment by David-Baddeley** [comment]
I think you'd have to bind them in the playback panel (the parent window), which is kinda gross. Whatever you bind them to has to be able to capture focus. Would need to test for OSX/darwin and special case as windows and linux are likely to get confused as they handle these things properly.

**Comment by zacsimile** [comment]
Oh sorry, I did bind `EVT_KEY_DOWN` in the `PlayPanel`. I put a print statement in the bound function, but it was never called.

**Comment by David-Baddeley** [comment]
Just checked on my OSX, and pgdown/pgup  (fn+arrow_down, fn+arrow_up) work even after clicking in the playback panel, which means that nothing in the playback panel captures focus so they are still handled by the main viewer. This is obviously desireable, and we might not want to do anything. Not sure I'd want to bind the straight arrows, however, as they might be used for something else (at one point they changed x and y positions, although I might have changed that to the "gamer" combos of either asdw or jkli)

**Pull request merged**
