### PR TITLE
Cropping refactor

### LINKED ISSUE #1129: [BUG] `dh5view` File > Export Cropped not working as expected
I tried to export cropped a single z-slice, 2048x2048 image with 6 color channels. I received the following traceback. Even if each pixel was a double, I think this should still only be ~201 MB. Feels like maybe export cropped isn't working as expected.

image

```
 Error whilst running File>&Export Cropped
==============================================
python-microscopy=21.09.23
python=3.7.11, platform=win32
numpy=1.21.1, wx=4.0.7.post2 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "c:\users\zrc4\code\python-microscopy\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "c:\users\zrc4\code\python-microscopy\PYME\DSView\dsviewer.py", line 363, in OnExport
    self.image.Save(crop = True, roi=roi)
  File "c:\users\zrc4\code\python-microscopy\PYME\IO\image.py", line 1318, in Save
    dataExporter.CropExportData(self.data_xyztc, roi, self.mdh, self.events, self.seriesName)
  File "c:\users\zrc4\code\python-microscopy\PYME\IO\dataExporter.py", line 621, in CropExportData
    exp.Export(data, filename, dlg.GetXSlice(), dlg.GetYSlice(), dlg.GetZSlice(),mdh, events, origName)
  File "c:\users\zrc4\code\python-microscopy\PYME\IO\dataExporter.py", line 288, in Export
    raise RuntimeError('TIFF has a maximum file size of 4GB, crop data or save as HDF')
RuntimeError: TIFF has a maximum file size of 4GB, crop data or save as HDF
```

### PR DESCRIPTION
**Pull request by David-Baddeley**
Hopefully fixes #1129, generally makes things much cleaner

### CODE REVIEW

**Comment by David-Baddeley** [comment]
# TODOs

- make cropped image export use `crop_image()` so that origin is correct for cropped image:
    - move `CropExportData` and associated dialog out of IO and into dh5view?
    - possibly remove `CropExportData` entirely - just have the dialog and then call `crop_image(image, roi).save()` from GUI handler code
    - remove all slice handling in the exporters themselves???
- cropping recipe module

**Comment by David-Baddeley** [comment]
@zacsimile - try giving this a spin.

**Comment by zacsimile** [comment]
Sorry, I missed this request. Just tested and it works for both `.h5` and `.tif`. This appears to fix the issue #1129.

Side note: If I load the `.tif` in ImageJ it still loads flat (color and z get compressed to z), but that's a different issue.

**Comment by David-Baddeley** [comment]
With ImageJ .tiff loading - does it work correctly with the bioformats importer - if so, then this is a long-running ImageJ bug rather than anything on our end.

**Comment by zacsimile** [comment]
It does not work correctly with the bioformats importer.

**Comment by David-Baddeley** [comment]
hmm - that is odd, and potentially a new bug - I thought we had that nailed

**Comment by zacsimile** [comment]
This is on Windows 10/ImageJ 1.53f51.

**Comment by David-Baddeley** [comment]
Mac, ImageJ 2.1.0/1.53c works fine, even just dragging and dropping (no bioformats import)

**Comment by David-Baddeley** [comment]
Bioformats importer also works as expected

**Comment by David-Baddeley** [comment]
Note - drag and drop only works if you've enabled the scifio importer (Edit->options->ImageJ2)

**Comment by zacsimile** [comment]
OK drag-and-drop works on my Windows if I enable SCIFIO, but Bioformats still does not work.

**Comment by David-Baddeley** [comment]
Super odd ...

**Pull request merged**
