### PR TITLE
Better contour plotting

### PR DESCRIPTION
**Pull request by zacsimile**
Addresses issue all the contours plot in the upper-left plot only (see screenshot).

Before this fix:
before_spt

After this fix:
after_spt

For a lot of SPT plots, this works. For some, the plots are still wonky, and I'm not sure why. Way more work this fix then worked before though (zero).

**Is this a bugfix or an enhancement?**
Bugfix

**Proposed changes:**
- Center contours on their respective images with `x0`, `y0`

**Checklist:**

- [ ] Tested with numpy=1.14
- [ ] Tested on python 2.7 and 3.6
- [ ] Tested with wx=3.x and wx=4.x [if UI code]
- [ ] Does the PR avoid variable renaming in existing code, whitespace changes, and other forms of tidying? [There is a place for code tidying, but it makes reviewing 
much simpler if this is kept separate from functional changes]

If an enhancement (or non-trivial bugfix):

- [ ] Has this been discussed in advance (feature request, PR proposal, email, or direct conversation)?
- [ ] Does this change how users interact with the software? How will these changes be communicated?
- [ ] Does this maintain backwards compatibility with old data?
- [ ] Does this change the required dependencies?
- [ ] Are there any other side effects of the change?

### CODE REVIEW

**Comment by David-Baddeley** [comment]
Looks reasonable, but I think you'll want to adjust the recipe quite a bit for that data (objects look too small/dim for threshold based detection and Measure2D to work well. Very quick flowchart which I should really format nicely for the docs below.

image

**Comment by David-Baddeley** [comment]
**Note:** if you use the feature based tracking on the output of a Gaussian fit, you can use both amplitude and width as features to help resolve ambiguous linkages.

**Comment by zacsimile** [comment]
Thanks for the flow chart! This is definitely not how I'd like to track data, but I just ran with some default settings for contour testing 'cause it takes less time. The contour plotting does work much better with this fix.

**Comment by David-Baddeley** [comment]
Just as a note, axes also look flipped in y (the top row should be a complete row, the bottom row should be a partial row). I wonder if a bunch of defaults changed in a recent matplotlib update (would also explain how things ended up in the wrong place in the photophysics stuff)

**Pull request merged**
