### PR TITLE
extend default directory listing and get_file timeouts

### PR DESCRIPTION
**Pull request by barentine**
Addresses issue #741 

**Is this a bugfix or an enhancement?**
makeshift bugfix?
**Proposed changes:**
- extend timeouts on clusterIO.get_file and clusterIO._listSingleDir

**Checklist:**

- [x] Tested

### CODE REVIEW

**Comment by barentine** [comment]
works like a charm. ~400x 20k series in with no failures

**Comment by barentine** [comment]
note that for a throttled push script to avoid difficulties encountered with #789, increasing the put_file timeout from 1 s to 5 s is also helpful

**Comment by David-Baddeley** [comment]
I'm a bit nervous about increasing the timeouts as we rely on the operations completing quickly for consistency. On some level, increasing timeouts simply masks the fact that something is not working properly. I wonder if a reasonable compromise might be to increase the timeouts, but also log an error/warning if the operation takes longer than the original timeouts (or potentially a reduced value in the directory listing case, which has already been increased). For `put_file` at least, we already calculate `dt`.

**Comment by barentine** [comment]
Long term I think we might need to make things somewhat adaptive. Everything worked great for 10k frames per series, got strained at 20k, and at 40k is just a disaster. People will surely want to crank longer series than that. Unless we implement an internal/hidden chunking in clusterIO, we'll probably need to rework something

**Comment by David-Baddeley** [comment]
Slightly reduced version merged with #796, as the history on this was a bit messed up and it was easier to start from scratch.

I'm not at all convinced that increasing cache sizes will make for a meaningful improvement in performance and would want that to be well argued. I think they are already pretty generously sized compared to their lifetimes.

**Pull request closed without merging**
