### PR TITLE
fix bakeshop drag and drop and appearance on MSW

### PR DESCRIPTION
**Pull request by David-Baddeley**
Work around odd DND behaviour and appearance on MSW

(both control and it's parent need to set drop target on windows)

### CODE REVIEW

**Comment by zacsimile** [comment]
Drag and drop on bakeshop doesn't work for me on Windows.

`conda run bakeshop`

Drag a file on top of the `FileListPanel` and I get a circle with a line through it. Can't drop the file.

**Comment by David-Baddeley** [comment]
That's super odd - this PR should fix exactly that problem (and was developed and tested on MSW)

**Comment by zacsimile** [comment]
Carmen brought it to my attention yesterday and I duplicated it on my machine today.

**Comment by zacsimile** [comment]
Doesn't work on MSWin10 enterprise 10.0.19041.

<details>
<summary>Package list</summary>
<pre>
# packages in environment at C:\Users\zrc4\Miniconda3\envs\pyme:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bleach                    3.3.0                    pypi_0    pypi
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.4.13            haa95532_1
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
cheroot                   8.5.2                    pypi_0    pypi
cherrypy                  18.6.0                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
conda                     4.10.1           py38haa244fe_0    conda-forge
conda-build               3.21.4           py38haa244fe_0    conda-forge
conda-package-handling    1.7.3            py38h31c79cd_0    conda-forge
cryptography              3.4.7            py38hd7da0ea_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
enum-compat               0.0.3                    pypi_0    pypi
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
future                    0.18.2                   pypi_0    pypi
glob2                     0.7                        py_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        4.0.1                    pypi_0    pypi
importlib-resources       5.1.3                    pypi_0    pypi
ipykernel                 5.5.5                    pypi_0    pypi
ipython                   7.23.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
jaraco-classes            3.2.1                    pypi_0    pypi
jaraco-collections        3.3.0                    pypi_0    pypi
jaraco-functools          3.3.0                    pypi_0    pypi
jaraco-text               3.5.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.0              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libarchive                3.5.1                h8686738_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblief                   0.10.1               ha925a31_2    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.0            py38h294d835_0    conda-forge
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
menuinst                  1.4.16           py38h32f6830_1    conda-forge
mistune                   0.8.4                    pypi_0    pypi
more-itertools            8.7.0                    pypi_0    pypi
mpld3                     0.5.2                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nest-asyncio              1.5.1                    pypi_0    pypi
netifaces                 0.10.9                   pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
notebook                  6.3.0                    pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.20.3                   pypi_0    pypi
oidic                     0.0.0                     dev_0    <develop>
openssl                   1.1.1k               h8ffe710_0    conda-forge
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pco                       0.1.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.7.0              pyhd8ed1ab_0    conda-forge
portend                   2.7.1                    pypi_0    pypi
prometheus-client         0.10.1                   pypi_0    pypi
prompt-toolkit            3.0.18                   pypi_0    pypi
psutil                    5.8.0            py38h294d835_1    conda-forge
py-lief                   0.10.1           py38h4b9bc1a_2    conda-forge
pycosat                   0.6.3           py38h294d835_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyface                    7.3.0                    pypi_0    pypi
pyfftw                    0.12.0                   pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pyme-4pi                  0.0.0                     dev_0    <develop>
pymecompress              0.2.0                    py38_0    local
pyopengl                  3.1.5                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.10          h7840368_1_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python-libarchive-c       2.9              py38haa244fe_2    conda-forge
python-microscopy         21.6.23                   dev_0    <develop>
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   300              py38h294d835_0    conda-forge
pywinpty                  0.5.7                    pypi_0    pypi
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.0.3                   pypi_0    pypi
qtconsole                 5.1.0                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ripgrep                   12.1.1               h301d43c_1    conda-forge
ruamel_yaml               0.15.100         py38h2bbff1b_0
scikit-image              0.18.1                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                52.0.0           py38haa95532_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.1.0                    pypi_0    pypi
soupsieve                 2.2.1              pyhd3eb1b0_0
sphinx                    3.5.4                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.35.5               h8ffe710_0    conda-forge
tables                    3.6.1                    pypi_0    pypi
tempora                   4.0.2                    pypi_0    pypi
terminado                 0.9.5                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2021.4.8                 pypi_0    pypi
toposort                  1.6                      pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                    pypi_0    pypi
traits                    6.2.0                    pypi_0    pypi
traitsui                  7.1.0                    pypi_0    pypi
ujson                     4.0.2                    pypi_0    pypi
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1                    pypi_0    pypi
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
wxpython                  4.1.1                    pypi_0    pypi
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zc-lockfile               2.0                      pypi_0    pypi
zeroconf                  0.17.7                   pypi_0    pypi
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge
</pre>
</details>

Dunno why I've got all this conda-forge. Let me see if I can try wtihout.

**Comment by David-Baddeley** [comment]
Yeah - this was supposed to fix Carmen's issue. Was also Win10 enterprise that I tested on :(. I know this is a dumb question, but are you certain you're running the most recent code (i.e. did you pull before testing)?

**Comment by zacsimile** [comment]
I am sure, yeah. Rebuilt, too, jic.

**Comment by zacsimile** [comment]
She also tried with the latest code this morning--she screenshared with me and I saw her `git pull` and update.

**Comment by David-Baddeley** [comment]
Super odd - because it was definitely working earlier - will head back in and re-test later today.

**Comment by zacsimile** [comment]
Which `wxpython` did you test it on?

**Comment by zacsimile** [comment]
Wait, wait. I `git pull`ed. I didn't `git fetch upstream master`. Just did that and it appears to work.

Would Carmen have been on a fork as well?

**Comment by zacsimile** [comment]
No, I know what happened. She didn't uninstall the packaged version of pyme and it superseded. OK, I'll contact her and let her know how to fix it. Sorry for spooking you.

**Comment by David-Baddeley** [comment]
Alternatively, I can trigger another packaged build (which had been on my TODO list for today anyway, as this is a fairly major regression) ...

**Comment by zacsimile** [comment]
Probably a good idea. However, I did email her with instructions on how to fix it already.

**Comment by David-Baddeley** [comment]
I'm currently working through a whole heap of regressions that I found when trying to run some old vesicle fusion code (to be fair last time it ran was on py2.7) so can hopefully get this in for  new build.

**Pull request merged**
