### PR TITLE
Make tabular.keys() return a list

### PR DESCRIPTION
**Pull request by zacsimile**
Addresses issue #674.

**Is this a bugfix or an enhancement?**
Bugfix

**Proposed changes:**
- `dict` types were causing us to index into the wrong parts of memory in py3 (`GetValue`), switched to `list`

**Additional notes**
We'll want to re-trigger package building after accepting this fix.

### CODE REVIEW

**Comment by David-Baddeley** [comment]
Would it be better to make `tabular.keys()` return a list so we don't run into this elsewhere?

I struggle to see how this could be causing a segfault though.

**Comment by zacsimile** [comment]
It would be useful to make `tabular.keys()` return a list. I think it's segfaulting in `GetValue` on ` str(self._tabular[self._tabular.keys()[col]][row])`. We know `self._tabular.keys()[col]` fails, but then it still tries to index into `self._tabular`. Also supporting this theory: changing this line got rid of the segfault.

**Comment by David-Baddeley** [comment]
There's still no way it should segfault (unless there is a particularly nasty python or numpy bug). The iterator / list issue should cause a python exception which can be handled as other exceptions are. It may not matter, but I'm pretty sure we're not fixing the segfault here.

**Comment by zacsimile** [comment]
Won't it return a number associated with the error and then try to index into tabular with that? I guess it might not, it might just get handled like a normal error.

Either way, there was a segfault, and there isn't after changing this line (the other line change fixed the `TypeError: 'odict_keys' object is not subscriptable` error). I'm about to pass a different fix where I change the tabular keys that were not lists to lists.

**Comment by David-Baddeley** [comment]
Nope, it will raise an exception - the array will never be indexed. Even if the array was indexed, numpy should catch any out of bounds errors.

My suspicion is that this is actually a wx error (wx has a habit of segfaulting when things don't go it's way) caused by an exception being thrown in out handler).

**Comment by zacsimile** [comment]
Ah, fair enough. I forgot about the `IndexError`. I agree, it shouldn't segfault from indexing. Must be in `wx`.

**Pull request merged**
