### PR TITLE
update checking

### PR DESCRIPTION
**Pull request by David-Baddeley**
Preliminary work on #483, #1041

### TODOs

- put current_version.json on the website
- make it update when we make a release
- have an opt-out after being prompted once to update
- add a check_for_updates menu item or "an update is available" menu item.
- have a global opt-out?
- actually call this when launching programs.

### CODE REVIEW

**Comment by David-Baddeley** [comment]
image

image

(currently have `current_version.json` set to something that triggers the message for testing)

**Comment by zacsimile** [comment]
Looks like a solid start! Thanks, @David-Baddeley.

**Comment by David-Baddeley** [comment]
Have added automatic checking, and a config option to opt-out. @zacsimile, @csoeller - Might be good to get some feedback as to whether we are too pushy / not pushy enough. As it stands.

- we check for updates each time you launch PYMEVis or PYMEImage (implicitly also if you launch PYMEAcquire, but that doesn't prompt by default). This can be disabled by setting the `PYME.config` `check_for_updates` key to `False`.
- if (and only if) we have not already prompted for the new version, we display a dialog which says that there is a new version. This dialog will only ever get shown once across all PYME programs for each update.
- We have added an option to the `Help` menu to manually check for updates. This will always show the update dialog if an update is available.
- if an update is available, we also add a menu item to the `Help` menu, called `Update to xx.xx.xx`. For now the functionality is completely equivalent to `Check for updates`.

The open questions:
- are we being too conservative with only prompting once - should we offer 'ignore' (which delays for a day) and 'don't ask again' options instead.
- will the http requests slow down opening too much? We might open the programs a lot, and this could get annoying if, e.g. you are not on a network and you have to wait for the request to time out. Should we, e.g. limit our queries to once per day instead?
- Can we use this to do user-number estimation for grant reporting etc ... (do we need to send some form of unique ID with the request?, how can we do this without compromising user privacy?).

**Comment by csoeller** [comment]
This looks very good @David-Baddeley, I gave it a try yesterday.

In terms of feedback on the general approach:

- I would be tempted to take a page out of the Fiji book, i.e. have a a button `Remind me later` that ensures another check is auto-performed >24h later or similar
- for now leave the config variable as the main way to completely disable automatic checks, in future possibly add an `Options` menu entry that allows GUI setting of config variables, including this one
- in the mid future add a button `update` to the message that invokes the functionality linked to  menu entry `Update to xx.xx.xx` once that actually can perform an update
- as you say an `don't ask again` button that disables checking until the next new version has come out and brings up a message box that says so (i.e. not `don't ask again ever` which would remain as the config variable functionality).
- I'd opt for the "once per day" checking limit in any case as this could otherwise become too annoying

I am sure some points can be debated.

The user statistics seem interesting but I would be paranoid that not accidentally some kind of privacy invasion can be construed by users (I know you mention that point). This could hurt uptake quite strongly.

**Comment by zacsimile** [comment]
I agree with all of @csoeller's recommendations. 

One way of getting user statistics might be to just count the number of fetch requests for each version of PYME. Presumably unique users aren't downloading this too many times (obviously there will be some multiple downloads, but not too many version-to-version). Certainly unique installs are unlikely to upgrade more than once.

**Comment by David-Baddeley** [comment]
We tried the fetch requests route for the CZI grant - with 4+ different ways people can get the package it was almost impossible to get meaningful data out of it. I really would like to have a more robust (i.e. actually usable) way of estimating user numbers, and think this is critical for ensuring that continued development is supported. 

If we do add a unique ID to the update checks, I'd want to make it a deliberate user choice (i.e. present a dialog before sending the info the first time). Tentative dialog text as follows:

----------------------

### Help us ensure that PYME development is supported

When applying for funding to support PYME development, it is very important to have a good estimate of user numbers. To facilitate this, we would like to send the following information with update requests:

**A unique installation identifier:** A random number generated the first time PYME checks for updates, this enables us to count the number of computers that are requesting updates. We do not link this identifier to any personal data, and by using a random number that is unique to PYME, rather than e.g. a MAC address, make it hard for a 3rd party to make such links. 

**The version of PYME you are currently using:** This gives us information to help decide when it is safe to e.g. deprecate old features.

----------------------
Pretty much every package that does automated update checking sends some user information - a lot of packages (Windows, MacOS, Chrome, Word, Anything from Adobe, etc ... are much, much more intrusive).

**Comment by David-Baddeley** [comment]
Moved to #1050 to keep git history sane

**Pull request closed without merging**
