### PR TITLE
Dark mode traits

### PR DESCRIPTION
**Pull request by David-Baddeley**
Very partial solution for issue #1331 .

Introduces a way of monkey-patching traitsui in order to define suitable text editor background colours so that text is visible in dark mode.

### CODE REVIEW

**Comment by zacsimile** [comment]
Confirmed working on my Mac as well. Thanks! 
image

**Comment by David-Baddeley** [comment]
closes #1499

**Comment by barentine** [comment]
Thanks for this, @David-Baddeley ! Is there a small namespace issue here? 
when running PYMEVis:
```
Traceback (most recent call last):
  File "c:\userfiles\andrew\code\python-microscopy\PYME\LMVis\VisGUI.py", line 431, in OnInit
    self.main = VisGUIFrame(None, self.filename, use_shaders=self.use_shaders, cmd_args=self.cmd_args)
  File "c:\userfiles\andrew\code\python-microscopy\PYME\LMVis\VisGUI.py", line 84, in __init__
    AUIFrame.__init__(self, parent, id, title, pos, size, style)
  File "c:\userfiles\andrew\code\python-microscopy\PYME\ui\AUIFrame.py", line 21, in __init__
    self._mgr = aui.AuiManager(agwFlags = aui.AUI_MGR_DEFAULT | aui.AUI_MGR_AUTONB_NO_CAPTION)
  File "C:\Users\aesb\Miniconda3\envs\pymedev\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 4137, in __init__
    self._art = dockart.AuiDefaultDockArt()
  File "C:\Users\aesb\Miniconda3\envs\pymedev\lib\site-packages\wx\lib\agw\aui\dockart.py", line 154, in __init__
    self.Init()
  File "c:\userfiles\andrew\code\python-microscopy\PYME\ui\patch_traitsui.py", line 134, in Init
    self.SetDefaultColours()
  File "C:\Users\aesb\Miniconda3\envs\pymedev\lib\site-packages\wx\lib\agw\aui\dockart.py", line 222, in SetDefaultColours
    base_colour = GetBaseColour()
  File "c:\userfiles\andrew\code\python-microscopy\PYME\ui\patch_traitsui.py", line 83, in GetBaseColour
    base_colour = aui_utilities.StepColour(base_colour, 92)
NameError: name 'aui_utilities' is not defined
```

**Comment by David-Baddeley** [comment]
@barentine - what version(s) of python and wx are you using? `aui_utilities` is imported up on line 27, and there is no issue on mac (python 3.8).

**Comment by barentine** [comment]
@David-Baddeley - yeah I saw that, and it imports fine in a shell / doesn't get clobbered by the `from wx.lib.agw.aui.aui_utilities` on the next line either.

```
# Name                    Version                   Build  Channel
python                    3.7.16               h6244533_0    anaconda
traitlets                 5.7.1            py37haa95532_0    anaconda
traits                    6.2.0            py37h2bbff1b_0    anaconda
traitsui                  7.1.0                      py_0    anaconda
wxpython                  4.0.4            py37ha925a31_0    anaconda
```

**Comment by barentine** [comment]
Had a reboot and fresh `setup.py develop`, same issue. Printing dir() output just before the name error results in `['base_colour']`.

Regardless, I see now that we essentially require wxpython 4.1 or higher with the `wx.SystemSettings().GetAppearance()` call ([wxpython docs](https://docs.wxpython.org/wx.SystemSettings.html?highlight=systemsettings#wx.SystemSettings.GetAppearance)). So maybe it is not worth me trying more on a wx 4.0.4 version

We'll want to update requirements.txt, and the conda recipes

**Comment by barentine** [comment]
I was on windows. A labmate just gave this all a shot on python 3.7, with wxpython 4.1, and hit the name error where aui_utilities is not present.

**Comment by barentine** [comment]
@David-Baddeley what version of wxpython are you using?

**Comment by Yujin-Bao** [comment]
Hi everyone! I just updated and gave it a try on this. I had the same issue. I am running python 3.7.11 with wxpython 4.1.1.

**Pull request merged**
