### PR TITLE
Convert display name for mean and Gaussian curvature from H and K to …

### PR DESCRIPTION
**Pull request by zacsimile**
…mean_curvature and gaussian_curvature

Addresses issue # .

**Is this a bugfix or an enhancement?**

**Proposed changes:**

**Checklist:**

- [ ] Tested with numpy=1.14
- [ ] Tested on python 2.7 and 3.6
- [ ] Tested with wx=3.x and wx=4.x [if UI code]
- [ ] Does the PR avoid variable renaming in existing code, whitespace changes, and other forms of tidying? [There is a place for code tidying, but it makes reviewing 
much simpler if this is kept separate from functional changes]

If an enhancement (or non-trivial bugfix):

- [ ] Has this been discussed in advance (feature request, PR proposal, email, or direct conversation)?
- [ ] Does this change how users interact with the software? How will these changes be communicated?
- [ ] Does this maintain backwards compatibility with old data?
- [ ] Does this change the required dependencies?
- [ ] Are there any other side effects of the change?

### CODE REVIEW

**Comment by David-Baddeley** [comment]
how would you feel about renaming to `curvature_mean` and `curvature_gaussian` so they appear together?

**Comment by zacsimile** [comment]
I'm torn. Logically, it makes more sense, but this was in direct response to Joerg asking us to make the options more user-friendly. I think people will get `curvature_mean`, but it's more confusing than `mean_curvature`. Currently `H` and `K` don't necessarily appear together... I think it's more user-friendly than `H` and `K`, but less user-friendly than `mean_curvature` and `gaussian_curvature`, but I'm fine switching it.

**Comment by David-Baddeley** [comment]
also torn, which is why I asked ... I'm not sure there's a good answer. As to usability, you could argue either way - people will probably look for `curvature` before `mean_curvature` and might take the first curvature they find which will be the Gaussian one. With the type as a suffix they'll sort to where people would expect curvature, they'll see both, and probably either go with mean because they don't know what Gaussian curvature is, or look it up - either of which will probably give them what they want.

**Comment by zacsimile** [comment]
Let's leave it as `curvature_mean` and `curvature_gaussian` for now.

**Pull request merged**
